---
- name: Grafana package
  community.general.pkgng:
    name: grafana9
    state: present

- name: Enable service
  community.general.sysrc:
    name: grafana_enable
    value: 'YES'
    state: present
  notify: Restart grafana

- name: Configure grafana
  ansible.builtin.lineinfile:
    path: /usr/local/etc/grafana/grafana.ini
    regexp: '^;?{{ item.name }} = '
    line: '{{ item.name }} = {{ item.value }}'
  with_items: '{{ grafana_settings }}'
  notify: Restart grafana
...
