---
- name: Jellyfin package
  community.general.pkgng:
    name: jellyfin
    state: present

- name: Enable jellyfin service
  community.general.sysrc:
    name: jellyfin_enable
    value: 'YES'
    state: present
  notify: Restart jellyfin

- name: Configure jellyfin data directory
  community.general.sysrc:
    name: jellyfin_data_dir
    value: '{{ jellyfin_data_dir }}'
    state: present
  notify: Restart jellyfin
  when: jellyfin_data_dir
...
