---
- name: unbound package
  community.general.pkgng:
    name: unbound
    state: present

- name: Enable unbound service
  community.general.sysrc:
    name: unbound_enable
    value: 'YES'
    state: present
  register: rc_enable

- name: Configure unbound
  ansible.builtin.template:
    src: unbound.conf.j2
    dest: /usr/local/etc/unbound/unbound.conf
  register: config

- name: Restart unbound service
  ansible.builtin.service:
    name: unbound
    state: restarted
  when: rc_enable.changed or config.changed
...
