---
- name: Unbound package
  community.general.pkgng:
    name: unbound
    state: present

- name: Enable unbound service
  community.general.sysrc:
    name: unbound_enable
    value: 'YES'
    state: present
  notify: Restart unbound

- name: Configure unbound
  ansible.builtin.template:
    src: unbound.conf.j2
    dest: /usr/local/etc/unbound/unbound.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: Restart unbound
...
