---
- name: Gitea package
  community.general.pkgng:
    name: gitea
    state: present

- name: Enable gitea service
  community.general.sysrc:
    name: gitea_enable
    value: 'YES'
    state: present
  notify: Restart gitea

- name: Configure gitea
  ansible.builtin.lineinfile:
    path: /usr/local/etc/gitea/conf/app.ini
    regexp: '^#?{{ item.name }}( *)= '
    line: '{{ item.name }}\1= {{ item.value }}'
    backrefs: yes
  with_items: '{{ gitea_settings }}'
  notify: Restart gitea
...
