---
- name: Node Exporter package
  community.general.pkgng:
    name: node_exporter
    state: present

- name: Enable service
  community.general.sysrc:
    name: node_exporter_enable
    value: 'YES'
    state: present
  notify: Restart node_exporter
...
