---
- name: Node Exporter package
  community.general.pkgng:
    name: node_exporter
    state: present

- name: Enable service
  community.general.sysrc:
    name: node_exporter_enable
    value: 'YES'
    state: present
  register: rc_enable

- name: Restart node_exporter service
  ansible.builtin.service:
    name: node_exporter
    state: restarted
  when: rc_enable.changed
...
