---
- name: VaultWarden package
  community.general.pkgng:
    name:
      - vaultwarden
    state: present

- name: Enable VaultWarden
  community.general.sysrc:
    name: vaultwarden_enable
    value: 'YES'
    state: present
  notify: Restart vaultwarden

- name: Create vaultwarden group
  ansible.builtin.group:
    name: '{{ vaultwarden_user }}'

- name: Create vaultwarden user
  ansible.builtin.user:
    name: '{{ vaultwarden_user }}'
    group: '{{ vaultwarden_user }}'
    home: /nonexistent
    shell: /usr/sbin/nologin

- name: Set vaultwarden user
  community.general.sysrc:
    name: vaultwarden_user
    value: '{{ vaultwarden_user }}'
    state: present
  notify: Restart vaultwarden

- name: Set vaultwarden group
  community.general.sysrc:
    name: vaultwarden_group
    value: '{{ vaultwarden_user }}'
    state: present
  notify: Restart vaultwarden

- name: Set vaultwarden directory
  community.general.sysrc:
    name: vaultwarden_chdir
    value: '{{ vaultwarden_directory }}'
    state: present
  notify: Restart vaultwarden
...
