---
- name: Manage users
  ansible.builtin.include_tasks: user.yml
  with_dict: '{{ users }}'
  loop_control:
    loop_var: user

- name: Manage static users
  ansible.builtin.include_tasks: user_static.yml
  with_dict: '{{ users_static }}'
  loop_control:
    loop_var: user

- name: Manage storage users
  ansible.builtin.user:
    name: '{{ item.key }}'
    groups: '{{ users_storage_group }}'
    append: true
  with_dict: '{{ users }}'
  when: users_storage_group
...
