---
- name: Enable NFS-related services
  community.general.sysrc:
    name: '{{ item }}'
    value: 'YES'
    state: present
  loop:
    - rpcbind_enable
    - rpc_lockd_enable
    - rpc_statd_enable
    - nfs_server_enable
    - mountd_enable
  notify: Restart NFS services

- name: Set NFS server arguments
  community.general.sysrc:
    name: nfs_server_flags
    value: '{{ nfsd_flags }}'
    state: present
  notify: Restart NFS services

- name: Exports configuration
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: wheel
    mode: '0644'
  notify: Restart NFS services
...
