---
- name: Prometheus package
  community.general.pkgng:
    name: prometheus
    state: present

- name: Enable service
  community.general.sysrc:
    name: prometheus_enable
    value: 'YES'
    state: present
  notify: Restart prometheus

- name: Set storage location
  community.general.sysrc:
    name: prometheus_data_dir
    value: '{{ prometheus_data_dir }}'
    state: "{{ prometheus_data_dir | ternary('present', 'absent') }}"
  notify: Restart prometheus

- name: Set storage retention time
  community.general.sysrc:
    name: prometheus_args
    value: '--storage.tsdb.retention.time={{ prometheus_retention_time }}'
    state: "{{ prometheus_retention_time | ternary('present', 'absent') }}"
  notify: Restart prometheus

- name: Configure prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /usr/local/etc/prometheus.yml
  notify: Restart prometheus
...
