---
- name: 'Generate certificate using cloudflare for {{ cert }}'
  ansible.builtin.command:
    cmd: >-
      certbot certonly
      --noninteractive --agree-tos
      --renew-hook 'service nginx reload'
      --dns-cloudflare
      --dns-cloudflare-credentials /usr/local/etc/letsencrypt/cloudflare_auth.ini
      -d {{ cert }} --email {{ web_proxy_certbot_email }}
    creates: '/usr/local/etc/letsencrypt/live/{{ cert | replace("*.", "") }}/cert.pem'
  notify: Restart nginx
...
