---
- name: 'Generate certificate using cloudflare for {{ vhost.name }}'
  ansible.builtin.command:
    cmd: >-
      certbot certonly
      --noninteractive --agree-tos
      --dns-cloudflare
      --dns-cloudflare-credentials {{ web_proxy_letsencrypt_directory }}/cloudflare/auth.ini
      --dns-cloudflare-propagation-seconds 30
      -d {{ vhost.name }} --email {{ certbot_email }}
    creates: '{{ web_proxy_letsencrypt_directory }}/live/{{ vhost.name }}/cert.pem'
  notify: Restart nginx
...
