---
- name: Bootstrap
  ansible.builtin.import_tasks: bootstrap.yml

- name: Generate certificate using Cloudflare validation
  ansible.builtin.include_tasks: generate-cert.yml
  with_items: '{{ web_proxy_certs }}'
  loop_control:
    loop_var: cert

- name: Configure NGINX vhosts
  ansible.builtin.include_tasks: vhost-proxy.yml
...
