---
- name: Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: Restart nginx
...
