---
- name: 'VHost configuration ({{ vhost.name }})'
  ansible.builtin.template:
    src: vhost-proxy.conf.j2
    dest: '{{ web_proxy_nginx_conf_directory }}/vhosts/{{ vhost.name }}.conf'
    owner: root
    group: wheel
    mode: '0644'
  notify: Restart nginx
...
