---
- name: Prowlarr package
  community.general.pkgng:
    name: prowlarr
    state: present

- name: Enable prowlarr service
  community.general.sysrc:
    name: prowlarr_enable
    value: 'YES'
    state: present
  notify: Restart prowlarr

- name: Configure prowlarr data directory
  community.general.sysrc:
    name: prowlarr_data_dir
    value: '{{ media_prowlarr_datadir }}'
  notify: Restart prowlarr
  when: media_prowlarr_datadir

- name: Create and chown prowlarr PID directory
  ansible.builtin.file:
    path: '{{ media_prowlarr_datadir }}/pid'
    state: directory
    owner: '{{ media_user }}'
    group: '{{ media_user }}'
    mode: '0775'
  notify: Restart prowlarr

- name: Configure prowlarr PID directory
  community.general.sysrc:
    name: prowlarr_pid_dir
    value: '{{ media_prowlarr_datadir }}/pid'
  notify: Restart prowlarr
  when: media_prowlarr_datadir

- name: Configure prowlarr user
  community.general.sysrc:
    name: prowlarr_user
    value: '{{ media_user }}'
  notify: Restart prowlarr

- name: Configure prowlarr group
  community.general.sysrc:
    name: prowlarr_group
    value: '{{ media_user }}'
  notify: Restart prowlarr

- name: Flush handlers to restart prowlarr service here
  ansible.builtin.meta: flush_handlers
...
