---
- name: Install recommended packages
  community.general.pkgng:
    name: '{{ item }}'
    state: present
  loop: '{{ base_packages }}'

- name: Remove outdated / unneeded packages
  community.general.pkgng:
    name: '{{ item }}'
    state: absent
  loop: '{{ base_packages_absent }}'

- name: Install additional packages
  community.general.pkgng:
    name: '{{ item }}'
    state: present
  loop: '{{ base_extra_packages }}'

- name: Disable sendmail
  community.general.sysrc:
    name: '{{ item }}_enable'
    value: 'NO'
    state: present
  loop:
    - sendmail
    - sendmail_submit
    - sendmail_outbound
    - sendmail_msp_queue
...
