---
galaxy_info:
  author: pegasd
  description: Base role to manage initial FreeBSD system configuration
  role_name: base
  license: BSD
  platforms:
    - name: FreeBSD
      versions: [ all ]
...
