---
- name: Plex package
  community.general.pkgng:
    name: plexmediaserver
    state: present

- name: Enable Plex service
  community.general.sysrc:
    name: plexmediaserver_enable
    value: 'YES'
    state: present
  notify: Restart Plex

- name: Configure Plex data directory
  community.general.sysrc:
    name: plexmediaserver_support_path
    value: '{{ plex_data_dir }}'
    state: present
  notify: Restart Plex
  when: plex_data_dir
...
