---
- name: 'Check if certificate for {{ vhost.name }} already exists'
  stat:
    path: '{{ letsencrypt_directory }}/live/{{ vhost.name }}/cert.pem'
  register: cert

- name: 'Generate certificate for {{ vhost.name }} (standalone)'
  ansible.builtin.command: >-
    certbot certonly
    --noninteractive --agree-tos
    --standalone
    --pre-hook {{ letsencrypt_directory }}/renewal-hooks/pre/stop_services
    --post-hook {{ letsencrypt_directory }}/renewal-hooks/post/start_services
    -d {{ vhost.name }} --email {{ certbot_email }}
  when: not cert.stat.exists
  register: sa_certgen

- name: 'Set changed flag ({{ vhost.name }})'
  ansible.builtin.set_fact:
    sa_certgen_changed: yes
  when: sa_certgen.changed
...
