---
- name: 'Check if certificate for {{ vhost.name }} already exists'
  stat:
    path: '{{ letsencrypt_directory }}/live/{{ vhost.name }}/cert.pem'
  register: cert

- name: 'Generate certificate for {{ vhost.name }}'
  ansible.builtin.command: '{{ certbot_create_command }}'
  when: not cert.stat.exists
...
