---
- include_tasks: bootstrap.yml
  when: enable_bootstrap

- include_tasks: generate-cert-standalone.yml
  with_items: '{{ vhosts }}'
  when:
    - cert_create_if_missing
  loop_control:
    loop_var: vhost

- include_tasks: vhost-proxy.yml
  with_items: '{{ vhosts }}'
  loop_control:
    loop_var: vhost

- import_tasks: renew-cron.yml

- name: Restart nginx after all changes
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: restart_nginx
...
