---
- include_tasks: bootstrap.yml
  when: enable_bootstrap
  register: bootstrap

- include_tasks: bootstrap-standalone.yml
  when: cert_create_method == 'standalone'
  register: sa_bootstrap

- include_tasks: bootstrap-cloudflare.yml
  when: cert_create_method == 'cloudflare'
  register: cf_bootstrap

- include_tasks: generate-cert-standalone.yml
  with_items: '{{ vhosts }}'
  when:
    - cert_create_if_missing
    - cert_create_method == 'standalone'
  loop_control:
    loop_var: vhost
  register: sa_cert_gen

- include_tasks: generate-cert-cloudflare.yml
  with_items: '{{ vhosts }}'
  when:
    - cert_create_if_missing
    - cert_create_method == 'cloudflare'
  loop_control:
    loop_var: vhost
  register: cf_cert_gen

- include_tasks: vhost-proxy.yml
  with_items: '{{ vhosts }}'
  loop_control:
    loop_var: vhost
  register: vhost_config

- import_tasks: renew-cron.yml

- name: Restart nginx after all changes
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: restart_nginx and
        (
          bootstrap.changed or sa_bootstrap.changed or cf_bootstrap.changed or
          sa_cert_gen.changed or cf_cert_gen.changed or vhost_config.changed
        )
...
