---
- name: Cron job for certificate renewal
  ansible.builtin.cron:
    name: letsencrypt renew
    job: certbot renew
    minute: '{{ cert_renew_cron_minute }}'
    hour: '{{ cert_renew_cron_hour }}'
    weekday: '{{ cert_renew_cron_weekday }}'
    user: root
    state: "{{ cert_renew_cron | ternary('present', 'absent') }}"
...
