---
- name: 'Client config for {{ client.name }}'
  ansible.builtin.template:
    src: client.conf.j2
    dest: '{{ wireguard_conf_directory }}/clients_{{ wireguard_interface }}/{{ client.name }}.conf'
...
