---
- name: WireGuard packages
  community.general.pkgng:
    name: '{{ item }}'
    state: present
  loop:
    - wireguard
    - wireguard-tools
    - libqrencode

- name: WireGuard server configuration
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: '{{ wireguard_conf_directory }}/{{ wireguard_interface }}.conf'

- name: Directory for client configs
  ansible.builtin.file:
    path: '{{ wireguard_conf_directory }}/clients_{{ wireguard_interface }}'
    state: directory
    mode: '0700'
    owner: root
    group: wheel

- include_tasks: client-config.yml
  with_items: '{{ wireguard_clients }}'
  loop_control:
    loop_var: client

- name: Configure wireguard interface
  community.general.sysrc:
    name: wireguard_interfaces
    value: '{{ wireguard_interface }}'

- name: Enable and start wireguard
  ansible.builtin.service:
    name: wireguard
    enabled: yes
    state: reload
...
