---
- name: WireGuard packages
  community.general.pkgng:
    name: '{{ item }}'
    state: present
  loop:
    - wireguard
    - wireguard-tools
    - libqrencode

- name: WireGuard server configuration
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: '{{ wireguard_conf_directory }}/{{ wireguard_interface }}.conf'
    owner: root
    group: wheel
    mode: '0600'
  notify: Restart wireguard

- name: Directory for client configs
  ansible.builtin.file:
    path: '{{ wireguard_conf_directory }}/clients_{{ wireguard_interface }}'
    state: directory
    owner: root
    group: wheel
    mode: '0700'

- name: Client configuration files
  ansible.builtin.template:
    src: client.conf.j2
    dest: '{{ wireguard_conf_directory }}/clients_{{ wireguard_interface }}/{{ client.name }}.conf'
    owner: root
    group: wheel
    mode: '0640'
  loop: '{{ wireguard_clients }}'
  loop_control:
    loop_var: client

- name: Enable wireguard
  community.general.sysrc:
    name: wireguard_enable
    value: 'YES'
    state: present
  notify: Restart wireguard

- name: Configure wireguard interface
  community.general.sysrc:
    name: wireguard_interfaces
    value: '{{ wireguard_interface }}'
    state: present
  notify: Restart wireguard
...
