---
- name: WireGuard packages
  community.general.pkgng:
    name: '{{ item }}'
    state: present
  loop:
    - wireguard
    - wireguard-tools
    - libqrencode

- name: WireGuard server configuration
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: '{{ wireguard_conf_directory }}/{{ wireguard_interface }}.conf'
  register: config

- name: Directory for client configs
  ansible.builtin.file:
    path: '{{ wireguard_conf_directory }}/clients_{{ wireguard_interface }}'
    state: directory
    mode: '0700'
    owner: root
    group: wheel
  register: client_config_dir

- name: 'Client config for {{ client.name }}'
  ansible.builtin.template:
    src: client.conf.j2
    dest: '{{ wireguard_conf_directory }}/clients_{{ wireguard_interface }}/{{ client.name }}.conf'
  loop: '{{ wireguard_clients }}'
  loop_control:
    loop_var: client
  register: client_config

- name: Enable wireguard
  community.general.sysrc:
    name: wireguard_enable
    value: 'YES'
    state: present
  register: rc_enable

- name: Configure wireguard interface
  community.general.sysrc:
    name: wireguard_interfaces
    value: '{{ wireguard_interface }}'
    state: present
  register: rc_interfaces

- name: Restart wireguard service
  ansible.builtin.service:
    name: wireguard
    state: restarted
  when: config.changed or client_config_dir.changed or client_config.changed or rc_enable.changed or rc_interfaces.changed
...
